# This is a basic workflow to help you get started with Actions

name: Terraform Demo Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_AD_CLIENT_ID}}
          client-secret: ${{secrets.AZURE_AD_CLIENT_SECRET}}
          tenant-id: ${{secrets.AZURE_AD_TENANT_ID}}
          subscription_id: ${{secrets.AZURE_AD_SUBSCRIPTION_ID}}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.5.0
          # client-id: ${{secrets.AZURE_AD_CLIENT_ID}}
          # client-secret: ${{secrets.AZURE_AD_CLIENT_SECRET}}
          # tenant-id: ${{secrets.AZURE_AD_TENANT_ID}}
          # subscription_id: ${{secrets.AZURE_AD_SUBSCRIPTION_ID}}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # - name: Terraform Apply 
      #   uses: terraform apply --auto-approve

      

      
  

    
